/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One workflow discovered in the target repo or the user workflow directory.
 */
export interface EditorWorkflowSummary {
    /**
     * Workflow slug (its directory name).
     */
    'name': string;
    /**
     * The graph goal, when the workflow file declares one.
     */
    'goal'?: string;
    /**
     * Whether the workflow lives in the repo or the user workflow directory.
     */
    'source': EditorWorkflowSummarySourceEnum;
    /**
     * Repo-relative path of the workflow graph file (absolute for user workflows).
     */
    'path': string;
}

export const EditorWorkflowSummarySourceEnum = {
    PROJECT: 'project',
    USER: 'user'
} as const;

export type EditorWorkflowSummarySourceEnum = typeof EditorWorkflowSummarySourceEnum[keyof typeof EditorWorkflowSummarySourceEnum];
