/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Save a workflow file as one commit.
 */
export interface EditorWorkflowSaveRequest {
    /**
     * Absolute path of the target repo on the server host.
     */
    'repo': string;
    /**
     * Repo-relative path of the workflow graph file.
     */
    'path': string;
    /**
     * The full workflow graph source to write.
     */
    'fabro_source': string;
    /**
     * When present, the sibling workflow.toml is written with this content and committed alongside.
     */
    'toml_source'?: string;
    /**
     * Git blob oid the edit was based on. Omit when creating a new file. A mismatch with the file on disk refuses the save.
     */
    'base_oid'?: string;
    /**
     * The commit message.
     */
    'commit_message': string;
}
