/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The source of one workflow file, with conflict-detection metadata.
 */
export interface EditorWorkflowFileResponse {
    /**
     * Repo-relative path of the workflow graph file.
     */
    'path': string;
    /**
     * The workflow graph source (Graphviz DOT).
     */
    'fabro_source': string;
    /**
     * Repo-relative path of the sibling workflow.toml, when present.
     */
    'toml_path'?: string;
    /**
     * Contents of the sibling workflow.toml, when present.
     */
    'toml_source'?: string;
    /**
     * Git blob oid of the graph file content as read. Send it back on save for conflict detection.
     */
    'base_oid': string;
}
