/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One skill available to the skill picker.
 */
export interface EditorSkill {
    /**
     * The skill name, inserted as a slash command.
     */
    'name': string;
    /**
     * One-line description from the SKILL.md frontmatter.
     */
    'description': string;
    /**
     * The skill root directory the skill was discovered in.
     */
    'source': string;
}
