/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Branch and push status of the target repo.
 */
export interface EditorRepoStatusResponse {
    /**
     * The current branch, or null when HEAD is detached.
     */
    'branch'?: string;
    /**
     * Commits ahead of the upstream branch. Zero when there is no upstream.
     */
    'ahead': number;
    /**
     * Commits behind the upstream branch. Zero when there is no upstream.
     */
    'behind': number;
    /**
     * Whether the current branch has an upstream to push to.
     */
    'has_upstream': boolean;
}
