/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One validation diagnostic. A parse failure is reported as rule `parse` with severity `error`.
 */
export interface EditorDiagnostic {
    /**
     * The lint rule name, or `parse` for a parse failure.
     */
    'rule': string;
    'severity': EditorDiagnosticSeverityEnum;
    'message': string;
    /**
     * The node the diagnostic names, when it names one.
     */
    'node_id'?: string;
    /**
     * Source node of the edge the diagnostic names, when it names one.
     */
    'edge_from'?: string;
    /**
     * Target node of the edge the diagnostic names, when it names one.
     */
    'edge_to'?: string;
    /**
     * 1-based source line, when known.
     */
    'line'?: number;
    /**
     * 1-based source column, when known.
     */
    'column'?: number;
}

export const EditorDiagnosticSeverityEnum = {
    ERROR: 'error',
    WARNING: 'warning',
    INFO: 'info'
} as const;

export type EditorDiagnosticSeverityEnum = typeof EditorDiagnosticSeverityEnum[keyof typeof EditorDiagnosticSeverityEnum];
