/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SubmitAnswerSelectedRequest {
    /**
     * Single selected option answer.
     */
    'kind': SubmitAnswerSelectedRequestKindEnum;
    /**
     * Key of the selected option.
     */
    'option_key': string;
    /**
     * Optional freeform message accompanying the selected option. Human gates record it in the run context alongside the verdict.
     */
    'text'?: string;
}

export const SubmitAnswerSelectedRequestKindEnum = {
    SELECTED: 'selected'
} as const;

export type SubmitAnswerSelectedRequestKindEnum = typeof SubmitAnswerSelectedRequestKindEnum[keyof typeof SubmitAnswerSelectedRequestKindEnum];
