/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EditorPushResponse } from '../models';
// @ts-ignore
import type { EditorRepoStatusResponse } from '../models';
// @ts-ignore
import type { EditorSkillListResponse } from '../models';
// @ts-ignore
import type { EditorValidateRequest } from '../models';
// @ts-ignore
import type { EditorValidateResponse } from '../models';
// @ts-ignore
import type { EditorWorkflowFileResponse } from '../models';
// @ts-ignore
import type { EditorWorkflowListResponse } from '../models';
// @ts-ignore
import type { EditorWorkflowSaveRequest } from '../models';
// @ts-ignore
import type { EditorWorkflowSaveResponse } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
/**
 * EditorApi - axios parameter creator
 */
export const EditorApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Discovers SKILL.md files one level deep under the conventional skill roots (repo `.fabro/skills`, repo `skills`, repo `.claude/skills`, user `~/.claude/skills`, user `~/.agents/skills`).
         * @summary List skills for the skill picker
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEditorSkills: async (repo: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'repo' is not null or undefined
            assertParamExists('listEditorSkills', 'repo', repo)
            const localVarPath = `/api/v1/editor/skills`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (repo !== undefined) {
                localVarQueryParameter['repo'] = repo;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the workflows discovered in the target repo\'s `.fabro/workflows` directory (workflow.toml-keyed), plus user workflows.
         * @summary List workflows in a repo
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEditorWorkflows: async (repo: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'repo' is not null or undefined
            assertParamExists('listEditorWorkflows', 'repo', repo)
            const localVarPath = `/api/v1/editor/workflows`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (repo !== undefined) {
                localVarQueryParameter['repo'] = repo;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Pushes the target repo\'s current branch to its remote, non-interactively. Never forces.
         * @summary Push the repo\'s current branch
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pushEditorRepo: async (repo: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'repo' is not null or undefined
            assertParamExists('pushEditorRepo', 'repo', repo)
            const localVarPath = `/api/v1/editor/repo/push`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (repo !== undefined) {
                localVarQueryParameter['repo'] = repo;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the target repo\'s current branch and how many commits it is ahead of and behind its upstream.
         * @summary Repo branch and push status
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveEditorRepoStatus: async (repo: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'repo' is not null or undefined
            assertParamExists('retrieveEditorRepoStatus', 'repo', repo)
            const localVarPath = `/api/v1/editor/repo/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (repo !== undefined) {
                localVarQueryParameter['repo'] = repo;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the source of one workflow file (and its sibling workflow.toml when present) from the target repo, with the base blob oid used for conflict detection on save.
         * @summary Read a workflow file
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {string} path Repo-relative path of the workflow graph file.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveEditorWorkflowFile: async (repo: string, path: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'repo' is not null or undefined
            assertParamExists('retrieveEditorWorkflowFile', 'repo', repo)
            // verify required parameter 'path' is not null or undefined
            assertParamExists('retrieveEditorWorkflowFile', 'path', path)
            const localVarPath = `/api/v1/editor/workflow`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (repo !== undefined) {
                localVarQueryParameter['repo'] = repo;
            }

            if (path !== undefined) {
                localVarQueryParameter['path'] = path;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Writes the workflow file (and optionally its sibling workflow.toml), stages exactly those paths, and creates one commit. Refuses with a conflict when the file changed on disk since it was read. Pushing is a separate explicit operation.
         * @summary Save a workflow file as a commit
         * @param {EditorWorkflowSaveRequest} editorWorkflowSaveRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveEditorWorkflowFile: async (editorWorkflowSaveRequest: EditorWorkflowSaveRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'editorWorkflowSaveRequest' is not null or undefined
            assertParamExists('saveEditorWorkflowFile', 'editorWorkflowSaveRequest', editorWorkflowSaveRequest)
            const localVarPath = `/api/v1/editor/workflow`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(editorWorkflowSaveRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Parses the inline workflow source and runs the lint rules. A parse failure is returned as a single `parse` diagnostic with line and column.
         * @summary Validate workflow source
         * @param {EditorValidateRequest} editorValidateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateEditorWorkflowSource: async (editorValidateRequest: EditorValidateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'editorValidateRequest' is not null or undefined
            assertParamExists('validateEditorWorkflowSource', 'editorValidateRequest', editorValidateRequest)
            const localVarPath = `/api/v1/editor/workflow/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(editorValidateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EditorApi - functional programming interface
 */
export const EditorApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EditorApiAxiosParamCreator(configuration)
    return {
        /**
         * Discovers SKILL.md files one level deep under the conventional skill roots (repo `.fabro/skills`, repo `skills`, repo `.claude/skills`, user `~/.claude/skills`, user `~/.agents/skills`).
         * @summary List skills for the skill picker
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listEditorSkills(repo: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EditorSkillListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listEditorSkills(repo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EditorApi.listEditorSkills']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the workflows discovered in the target repo\'s `.fabro/workflows` directory (workflow.toml-keyed), plus user workflows.
         * @summary List workflows in a repo
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listEditorWorkflows(repo: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EditorWorkflowListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listEditorWorkflows(repo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EditorApi.listEditorWorkflows']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Pushes the target repo\'s current branch to its remote, non-interactively. Never forces.
         * @summary Push the repo\'s current branch
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pushEditorRepo(repo: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EditorPushResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pushEditorRepo(repo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EditorApi.pushEditorRepo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the target repo\'s current branch and how many commits it is ahead of and behind its upstream.
         * @summary Repo branch and push status
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveEditorRepoStatus(repo: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EditorRepoStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveEditorRepoStatus(repo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EditorApi.retrieveEditorRepoStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the source of one workflow file (and its sibling workflow.toml when present) from the target repo, with the base blob oid used for conflict detection on save.
         * @summary Read a workflow file
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {string} path Repo-relative path of the workflow graph file.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveEditorWorkflowFile(repo: string, path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EditorWorkflowFileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveEditorWorkflowFile(repo, path, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EditorApi.retrieveEditorWorkflowFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Writes the workflow file (and optionally its sibling workflow.toml), stages exactly those paths, and creates one commit. Refuses with a conflict when the file changed on disk since it was read. Pushing is a separate explicit operation.
         * @summary Save a workflow file as a commit
         * @param {EditorWorkflowSaveRequest} editorWorkflowSaveRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveEditorWorkflowFile(editorWorkflowSaveRequest: EditorWorkflowSaveRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EditorWorkflowSaveResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveEditorWorkflowFile(editorWorkflowSaveRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EditorApi.saveEditorWorkflowFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Parses the inline workflow source and runs the lint rules. A parse failure is returned as a single `parse` diagnostic with line and column.
         * @summary Validate workflow source
         * @param {EditorValidateRequest} editorValidateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateEditorWorkflowSource(editorValidateRequest: EditorValidateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EditorValidateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateEditorWorkflowSource(editorValidateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EditorApi.validateEditorWorkflowSource']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EditorApi - factory interface
 */
export const EditorApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EditorApiFp(configuration)
    return {
        /**
         * Discovers SKILL.md files one level deep under the conventional skill roots (repo `.fabro/skills`, repo `skills`, repo `.claude/skills`, user `~/.claude/skills`, user `~/.agents/skills`).
         * @summary List skills for the skill picker
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEditorSkills(repo: string, options?: RawAxiosRequestConfig): AxiosPromise<EditorSkillListResponse> {
            return localVarFp.listEditorSkills(repo, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the workflows discovered in the target repo\'s `.fabro/workflows` directory (workflow.toml-keyed), plus user workflows.
         * @summary List workflows in a repo
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEditorWorkflows(repo: string, options?: RawAxiosRequestConfig): AxiosPromise<EditorWorkflowListResponse> {
            return localVarFp.listEditorWorkflows(repo, options).then((request) => request(axios, basePath));
        },
        /**
         * Pushes the target repo\'s current branch to its remote, non-interactively. Never forces.
         * @summary Push the repo\'s current branch
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pushEditorRepo(repo: string, options?: RawAxiosRequestConfig): AxiosPromise<EditorPushResponse> {
            return localVarFp.pushEditorRepo(repo, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the target repo\'s current branch and how many commits it is ahead of and behind its upstream.
         * @summary Repo branch and push status
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveEditorRepoStatus(repo: string, options?: RawAxiosRequestConfig): AxiosPromise<EditorRepoStatusResponse> {
            return localVarFp.retrieveEditorRepoStatus(repo, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the source of one workflow file (and its sibling workflow.toml when present) from the target repo, with the base blob oid used for conflict detection on save.
         * @summary Read a workflow file
         * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
         * @param {string} path Repo-relative path of the workflow graph file.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveEditorWorkflowFile(repo: string, path: string, options?: RawAxiosRequestConfig): AxiosPromise<EditorWorkflowFileResponse> {
            return localVarFp.retrieveEditorWorkflowFile(repo, path, options).then((request) => request(axios, basePath));
        },
        /**
         * Writes the workflow file (and optionally its sibling workflow.toml), stages exactly those paths, and creates one commit. Refuses with a conflict when the file changed on disk since it was read. Pushing is a separate explicit operation.
         * @summary Save a workflow file as a commit
         * @param {EditorWorkflowSaveRequest} editorWorkflowSaveRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveEditorWorkflowFile(editorWorkflowSaveRequest: EditorWorkflowSaveRequest, options?: RawAxiosRequestConfig): AxiosPromise<EditorWorkflowSaveResponse> {
            return localVarFp.saveEditorWorkflowFile(editorWorkflowSaveRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Parses the inline workflow source and runs the lint rules. A parse failure is returned as a single `parse` diagnostic with line and column.
         * @summary Validate workflow source
         * @param {EditorValidateRequest} editorValidateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateEditorWorkflowSource(editorValidateRequest: EditorValidateRequest, options?: RawAxiosRequestConfig): AxiosPromise<EditorValidateResponse> {
            return localVarFp.validateEditorWorkflowSource(editorValidateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EditorApi - object-oriented interface
 */
export class EditorApi extends BaseAPI {
    /**
     * Discovers SKILL.md files one level deep under the conventional skill roots (repo `.fabro/skills`, repo `skills`, repo `.claude/skills`, user `~/.claude/skills`, user `~/.agents/skills`).
     * @summary List skills for the skill picker
     * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listEditorSkills(repo: string, options?: RawAxiosRequestConfig) {
        return EditorApiFp(this.configuration).listEditorSkills(repo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the workflows discovered in the target repo\'s `.fabro/workflows` directory (workflow.toml-keyed), plus user workflows.
     * @summary List workflows in a repo
     * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listEditorWorkflows(repo: string, options?: RawAxiosRequestConfig) {
        return EditorApiFp(this.configuration).listEditorWorkflows(repo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Pushes the target repo\'s current branch to its remote, non-interactively. Never forces.
     * @summary Push the repo\'s current branch
     * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public pushEditorRepo(repo: string, options?: RawAxiosRequestConfig) {
        return EditorApiFp(this.configuration).pushEditorRepo(repo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the target repo\'s current branch and how many commits it is ahead of and behind its upstream.
     * @summary Repo branch and push status
     * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public retrieveEditorRepoStatus(repo: string, options?: RawAxiosRequestConfig) {
        return EditorApiFp(this.configuration).retrieveEditorRepoStatus(repo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the source of one workflow file (and its sibling workflow.toml when present) from the target repo, with the base blob oid used for conflict detection on save.
     * @summary Read a workflow file
     * @param {string} repo Absolute path of the target repo on the server host. Must contain &#x60;.fabro/project.toml&#x60;.
     * @param {string} path Repo-relative path of the workflow graph file.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public retrieveEditorWorkflowFile(repo: string, path: string, options?: RawAxiosRequestConfig) {
        return EditorApiFp(this.configuration).retrieveEditorWorkflowFile(repo, path, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Writes the workflow file (and optionally its sibling workflow.toml), stages exactly those paths, and creates one commit. Refuses with a conflict when the file changed on disk since it was read. Pushing is a separate explicit operation.
     * @summary Save a workflow file as a commit
     * @param {EditorWorkflowSaveRequest} editorWorkflowSaveRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public saveEditorWorkflowFile(editorWorkflowSaveRequest: EditorWorkflowSaveRequest, options?: RawAxiosRequestConfig) {
        return EditorApiFp(this.configuration).saveEditorWorkflowFile(editorWorkflowSaveRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Parses the inline workflow source and runs the lint rules. A parse failure is returned as a single `parse` diagnostic with line and column.
     * @summary Validate workflow source
     * @param {EditorValidateRequest} editorValidateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public validateEditorWorkflowSource(editorValidateRequest: EditorValidateRequest, options?: RawAxiosRequestConfig) {
        return EditorApiFp(this.configuration).validateEditorWorkflowSource(editorValidateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
